Update player_upload_to_s3.yaml

diff --git a/.github/workflows/player_upload_to_s3.yaml b/.github/workflows/player_upload_to_s3.yaml
--- a/.github/workflows/player_upload_to_s3.yaml
+++ b/.github/workflows/player_upload_to_s3.yaml
@@ -136,7 +136,8 @@ jobs:
                       --output text))
           aws sts get-caller-identity
           s3Path="s3://${{ matrix.env }}-${{ secrets.PLAYER_S3_BUCKET_APPS }}/bundler/playkit/modules/${{ inputs.name }}/${{ inputs.version }}"
-          aws s3 cp package/dist/ ${s3Path}/ --recursive --exclude "*" --include "${{ inputs.name }}.js*"
+          echo "pappi: ${s3Path}"
+          aws s3 cp package/dist/ ${s3Path}/ --recursive --exclude "*" --include "${{ inputs.name }}.js*" && echo "we did it" || echo "cp failed"
           aws s3 ls ${s3Path}/
           if [ -d 'package/translations' ]; then
             aws s3 cp package/translations/ ${s3Path}/translations/ --recursive --include "*"
