align all variables and update deploy uiconf

diff --git a/.github/workflows/player_deploy_uiconf.yaml b/.github/workflows/player_deploy_uiconf.yaml
--- a/.github/workflows/player_deploy_uiconf.yaml
+++ b/.github/workflows/player_deploy_uiconf.yaml
@@ -16,7 +16,7 @@ on:
         required: true
         type: string
       env:
-        description: "env - example: 'qa/prod/all'"
+        description: "env - example: 'qa/prod'"
         required: false
         type: string
       version:
@@ -47,30 +47,23 @@ jobs:
           aws-region: "eu-central-1"
 
       - name: Get secret
-        id: secret-name
+        id: secret_name
         run: |
-          if [ "${{ inputs.stage }}" == "canary" ]; then
-            secret_name="uiconf-aws-dev-qa-accounts"
-          elif [ "${{ inputs.env }}" == "prod" ]; then
-            secret_name="uiconf-aws-all-accounts"
+          if [ "${{ inputs.env }}" = "prod" ]; then
+            secret_name="github-aws-all-accounts"
           else
-            exit 1
+            secret_name="github-aws-dev-qa-accounts"
           fi
 
           echo $secret_name
-          echo "secret-name=$secret_name" >> $GITHUB_OUTPUT
+          echo "secret_name=$secret_name" >> $GITHUB_OUTPUT
 
       - name: Get environments list
         id: accounts
         run: |
-          aws_envs=$(aws secretsmanager get-secret-value --secret-id  arn:aws:secretsmanager:eu-central-1:${{ secrets.CENTRAL_ACCOUNT_ID }}:secret:${{ steps.secret-name.outputs.secret-name }} --query SecretString --output text | jq -c .)
-          echo $aws_envs | jq -c '.[]' | while read i; do app_id=$(jq -r '.app_id' <<< "$i"); echo "::add-mask::$app_id"; done
-          echo $aws_envs | jq -c '.[]' | while read i; do app_token=$(jq -r '.app_token' <<< "$i"); echo "::add-mask::$app_token"; done
-          echo $aws_envs | jq -c '.[]' | while read i; do service_url=$(jq -r '.service_url' <<< "$i"); echo "::add-mask::$service_url"; done
-          echo $aws_envs | jq -c '.[]' | while read i; do partner_id=$(jq -r '.partner_id' <<< "$i"); echo "::add-mask::$partner_id"; done
-
+          aws_envs=$(aws secretsmanager get-secret-value --secret-id  arn:aws:secretsmanager:eu-central-1:${{ secrets.CENTRAL_ACCOUNT_ID }}:secret:${{ steps.secret_name.outputs.secret_name }} --query SecretString --output text | jq -c .)
+          echo $aws_envs | jq -c '.[]' | while read i; do account_id=$(jq -r '.account_id' <<< "$i"); echo "::add-mask::$account_id"; done
           accounts=$(echo $aws_envs | jq -c '.[]' | while read i; do jq -n --arg env "$(jq -r '.env' <<< "$i")" '{"env": $env}' ; done | jq -s -c .)
-
           echo $accounts
           echo "accounts=$accounts" >> $GITHUB_OUTPUT
 
@@ -78,22 +71,25 @@ jobs:
         run: |
           echo ${{ steps.accounts.outputs.accounts }} | jq -c '.[]' | while read i; do
             env_name="$(jq -r '.env' <<< "$i")"
-            filter_tags="autodeploy,${{ inputs.schema-type }}_${{ inputs.stage }},${{ inputs.schema-type }}_list,${{ inputs.schema-type }},${{ inputs.stage }}"
-            new_tags="autodeploy,${{ inputs.schema-type }}_${{ inputs.stage }},${{ inputs.schema-type }}_list,${{ inputs.version }},${{ inputs.schema-type }},${{ inputs.stage }}"
-            file_name="${{ inputs.file-name }}"
-            generate_post_data='{"secret_name": "${{ steps.secret-name.outputs.secret-name }}", "filter_tags": "${filter_tags}", "new_tags": "${new_tags}", "file_name": "${file_name}", "env": "${env_name}"}'
+            if [ ${env_name} = 'nvp1' ] || [ ${env_name} = 'nvq1' ]; then
+              filter_tags="autodeploy,${{ inputs.schema-type }}_${{ inputs.stage }},${{ inputs.schema-type }}_list,${{ inputs.schema-type }},${{ inputs.stage }}"
+              new_tags="autodeploy,${{ inputs.schema-type }}_${{ inputs.stage }},${{ inputs.schema-type }}_list,${{ inputs.version }},${{ inputs.schema-type }},${{ inputs.stage }}"
+              generate_post_data='{"secret_name": "${{ steps.secret_name.outputs.secret_name }}", "filter_tags": "${filter_tags}", "new_tags": "${new_tags}", "file_name": "${{ inputs.file-name }}", "env": "${env_name}"}'
 
-            aws lambda invoke --function-name ${{ secrets.LAMBDA_NAME }} --payload "${generate_post_data}" --cli-binary-format raw-in-base64-out response.json > /dev/null 2>&1
+              aws lambda invoke --function-name ${{ secrets.LAMBDA_NAME }} --payload "${generate_post_data}" --cli-binary-format raw-in-base64-out response.json > /dev/null 2>&1
 
-            status=$(jq -r '.status' response.json)
+              status=$(jq -r '.status' response.json)
 
-            echo "Running lambda on env ${env_name} finished:"
-            if [ "${status}" == "Success" ]; then
-              echo "Success"
-              jq -r '.' response.json
+              echo "Running lambda on env ${env_name} finished:"
+              if [ "${status}" = "Success" ]; then
+                echo "Success"
+                jq -r '.' response.json
+              else
+                echo "Failed"
+                jq -r '.' response.json
+                exit 1
+              fi
             else
-              echo "Failed"
-              jq -r '.' response.json
-              exit 1
+              echo "no uiconf on ${env_name}"
             fi
           done
