test

diff --git a/.github/workflows/player_deploy_kconf.yaml b/.github/workflows/player_deploy_kconf.yaml
--- a/.github/workflows/player_deploy_kconf.yaml
+++ b/.github/workflows/player_deploy_kconf.yaml
@@ -89,13 +89,20 @@ jobs:
           PARAMS=$(aws ssm get-parameters-by-path --path "${SCHEMA_PARAM_BASE_NAME}/${SCHEMA_TYPE}/${ENV_TYPE}-${STAGE}" --recursive --with-decryption --query 'Parameters[].[Name,Value]' 2>&1)
           PARAMS=$(echo "${PARAMS}" | jq -c 'reduce .[] as $item ({}; .[$item[0]] = $item[1])')
           echo "params=${PARAMS}" >> $GITHUB_OUTPUT
-  enumerate-environments:
-    name: Enumerate Environments
+  deploy-kconf:
+    name: Deploy KConf
     runs-on: ubuntu-latest
     needs: [retrieve-parameters]
     env:
+      PRODUCT_VERSION_PARAM_BASE_NAME: /player/versions/uiconf
+      SCHEMA_PARAM_BASE_NAME: /player/schema
+      PRODUCT_VERSION_YAML_BASE_NAME: .global.application.embedPlayKit.productVersions
+      PLAYKIT_VERSION_SCHEMA_BASE_NAME: .global.application.embedPlayKit.versions
+      SCHEMA_TYPE: ${{ inputs.schema-type }}
       ENV_TYPE: ${{ inputs.env }}
       STAGE: ${{ inputs.stage }}
+      PRODUCT_VERSION: ${{ needs.retrieve-parameters.outputs.product-version }}
+      PARAMS: ${{ needs.retrieve-parameters.outputs.params }}
     outputs:
       envs: ${{ steps.enumerate-environments.outputs.envs }}
     steps:
@@ -108,13 +115,15 @@ jobs:
         id: enumerate-environments
         run: |
           ENVIRONMENTS=()
-          JSON_ENVIRONMENTS=""
 
           function get_environments() {
             ENV_DELIMITER=$(echo "${1}" | cut -c1)
-            VALUES_FILES=$(find deployment/regions/ -regex "^deployment\/regions\/[a-zA-Z0-9_-]+\/[a-zA-z]+${ENV_DELIMITER}.\/[a-zA-Z0-9_-]+\/values.yaml" -type f)
-            ENVIRONMENT=$(echo "${VALUES_FILES}" | cut -d'/' -f4 | sort -u)
-            echo "${ENVIRONMENT}"
+            if [[ ${ENV_DELIMITER} == "p" ]]; then
+              VALUES_FILES="deployment/values.yaml"
+            else
+              VALUES_FILES=$(find deployment/regions/ -regex "^deployment\/regions\/[a-zA-Z0-9_-]+\/[a-zA-z]+${ENV_DELIMITER}.\/[a-zA-Z0-9_-]+\/values.yaml" -type f)
+            fi
+            echo "${VALUES_FILES}"
           }
 
           function add_environment() {
@@ -126,7 +135,7 @@ jobs:
 
           if [[ ${ENV_TYPE} != "" ]]; then
             echo "build for env ${ENV_TYPE}"
-            add_environment "$(get_environments "${ENV}")"
+            add_environment "$(get_environments "${ENV_TYPE}")"
           else
             for ENV in {dev,qa,prod}; do
               if [[ ${STAGE} == "canary" && ${ENV} == "prod" ]]; then
@@ -136,38 +145,28 @@ jobs:
               add_environment "$(get_environments "${ENV}")"
             done
           fi
-          JSON_ENVIRONMENTS=$(jq -c -n '$ARGS.positional' --args "${ENVIRONMENTS[@]}")
-          echo "envs=${JSON_ENVIRONMENTS}" >> $GITHUB_OUTPUT
-  deploy-kconf:
-    name: Deploy KConf
-    runs-on: ubuntu-latest
-    needs: [retrieve-parameters, enumerate-environments]
-    strategy:
-      matrix:
-        env: ${{ fromJSON(needs.enumerate-environments.outputs.envs) }}
-    env:
-      PRODUCT_VERSION_PARAM_BASE_NAME: /player/versions/uiconf
-      SCHEMA_PARAM_BASE_NAME: /player/schema
-      PRODUCT_VERSION_YAML_BASE_NAME: .global.application.embedPlayKit.productVersions
-      PLAYKIT_VERSION_SCHEMA_BASE_NAME: .global.application.embedPlayKit.versions
-      SCHEMA_TYPE: ${{ inputs.schema-type }}
-      STAGE: ${{ inputs.stage }}
-      PRODUCT_VERSION: ${{ needs.retrieve-parameters.outputs.product-version }}
-      PARAMS: ${{ needs.retrieve-parameters.outputs.params }}
-      ENVIRONMENT: ${{ matrix.env }}
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-        with:
-          repository: kaltura/embed-playkit-saas-config-generic
-          ref: main
+
+          echo "ENVIRONMENTS: ${ENVIRONMENTS[@]}"
+          echo "envs=${ENVIRONMENTS}" >> $GITHUB_OUTPUT
       - name: Update Helm Values
         id: update_schema
+        env:
+          ENVIRONMENTS: ${{ steps.enumerate-environments.outputs.envs }}
         run: |
-          echo "${ENVIRONMENT}"
-          VALUES_FILES=$(find deployment/regions/ -regex "^deployment\/regions\/[a-zA-Z0-9_-]+\/${ENVIRONMENT}\/[a-zA-Z0-9_-]+\/values.yaml" -type f)
-          echo "VALUES_FILES=${VALUES_FILES}"
-          for ENV in ${VALUES_FILES}; do
+          if ! [[ ${ENV_TYPE} =~ ^(dev|qa|prod)$ ]]; then
+            echo "invalid env_type: ${env_type} for env: ${env_name}"
+            exit 1
+          elif ! [[ ${STAGE} =~ ^(canary|beta|latest)$ ]]; then
+            echo "invalid stage: ${STAGE}"
+            exit 1
+          fi
+          for ENV in ${ENVIRONMENTS}; do
+            if [[ ${ENV} == "deployment/values.yaml" ]]; then
+              ENV_NAME="prod"
+            else
+              ENV_NAME=$(echo "${ENV}" | cut -d'/' -f5 | sort -u)
+            fi
+            echo "Running on ${ENV_NAME}"
             for PLAYKIT in $(echo "${PARAMS}" | jq -r 'keys[]'); do
               NAME=$(basename "${PLAYKIT}")
               VERSION=$(echo "${PARAMS}" | jq -r ".\"${PLAYKIT}\"")
@@ -179,15 +178,14 @@ jobs:
                 continue
               fi
           
-              echo "Updating ${ENV} with ${PLAYKIT_VERSION_PATH} = ${VERSION}"
-          
               yq "${PLAYKIT_VERSION_PATH} = \"${VERSION}\"" "${ENV}" -i
               if [[ $? -ne 0 ]]; then
                 echo "Failed to update ${ENV} with ${PLAYKIT_VERSION_PATH} = ${VERSION}"
                 exit 1
               fi
             done
-          
+            echo "${PLAYKIT_VERSION_PATH} = \"${VERSION}\""
+
             PRODUCT_VERSION_PATH="${PRODUCT_VERSION_YAML_BASE_NAME}.${SCHEMA_TYPE}.${STAGE}"
           
             yq "${PRODUCT_VERSION_PATH} = \"${PRODUCT_VERSION}\"" "${ENV}" -i
@@ -199,14 +197,14 @@ jobs:
             NEW_PRODUCT_VERSION=$(yq "${PRODUCT_VERSION_PATH}" "${ENV}" -r)
             echo "Successfully deployed new product version: ${NEW_PRODUCT_VERSION}"
           done
-      - name: Commit and push changes
+      - name: Commit and Push
+        id: commit-and-push
         run: |
-          git config --global user.name "github-actions[bot]"
-          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
           if [[ -z $(git status -s) ]]; then
             echo "No changes to commit"
             exit 0
           fi
-          git add .
-          git commit -am ":rocket: CI: Deploy ${SCHEMA_TYPE}-${STAGE} on ${ENV}"
+          git config --global user.email "github-ci@kaltura.com"
+          git config --global user.name "github-ci"
+          git commit -am ":rocket: CI: Deploy ${SCHEMA_TYPE}-${STAGE} on ${ENV_TYPE}"
           git push
