old ci compatibility

diff --git a/.github/workflows/player_deploy_kconf.yaml b/.github/workflows/player_deploy_kconf.yaml
--- a/.github/workflows/player_deploy_kconf.yaml
+++ b/.github/workflows/player_deploy_kconf.yaml
@@ -26,7 +26,7 @@ on:
 
 jobs:
   retrieve-parameters:
-    name: Retrieve Parameters
+    name: gather-kconf-build-details
     runs-on: ubuntu-latest
     permissions:
       id-token: write
@@ -90,7 +90,7 @@ jobs:
           PARAMS=$(echo "${PARAMS}" | jq -c 'reduce .[] as $item ({}; .[$item[0]] = $item[1])')
           echo "params=${PARAMS}" >> $GITHUB_OUTPUT
   deploy-kconf:
-    name: Deploy KConf
+    name: deploy-kconf
     runs-on: ubuntu-latest
     needs: [retrieve-parameters]
     env:
@@ -133,9 +133,12 @@ jobs:
             done
           }
 
-          if [[ ${ENV_TYPE} != "" ]]; then
-            echo "build for env ${ENV_TYPE}"
-            add_environment "$(get_environments "${ENV_TYPE}")"
+          if ! [[ ${ENV_TYPE} =~ ^(dev|qa|prod)$ ]]; then
+            echo "invalid env_type: ${env_type} for env: ${env_name}"
+            exit 1
+          elif ! [[ ${STAGE} =~ ^(canary|beta|latest)$ ]]; then
+            echo "invalid stage: ${STAGE}"
+            exit 1
           else
             for ENV in {dev,qa,prod}; do
               if [[ ${STAGE} == "canary" && ${ENV} == "prod" ]]; then
@@ -152,13 +155,6 @@ jobs:
         env:
           ENVIRONMENTS: ${{ steps.enumerate-environments.outputs.envs }}
         run: |
-          if ! [[ ${ENV_TYPE} =~ ^(dev|qa|prod)$ ]]; then
-            echo "invalid env_type: ${env_type} for env: ${env_name}"
-            exit 1
-          elif ! [[ ${STAGE} =~ ^(canary|beta|latest)$ ]]; then
-            echo "invalid stage: ${STAGE}"
-            exit 1
-          fi
           for ENV in ${ENVIRONMENTS}; do
             if [[ ${ENV} == "deployment/values.yaml" ]]; then
               ENV_NAME="prod"
